---
  - name: -> starting Ansible Managed for {{inventory_hostname}}
    debug: msg="{{inventory_hostname}} is already managed by Ansible"

  - name: -> Check the hostname {{inventory_hostname}} is present in dns...???
    shell: host {{ inventory_hostname }}
    register: is_hostname_present
    ignore_errors: true

  - name: -> Failed if hostname {{inventory_hostname}} is not correctly setup on target host.
    fail: msg="Hostname '{{inventory_hostname}}' is not correct, not matching with dns, please check on the host to correct it"
    when: is_hostname_present|failed


  - name: -> Get the IP 
    shell: host {{inventory_hostname}} | grep "address" |awk '{print $NF}'
    register: is_host_ip

  - name: -> Print host ip
    debug: "msg='{{ is_host_ip.stdout }}'"

  - name: -> Check the ip pointing to its host or not
    shell: host {{ is_host_ip.stdout }} | grep "{{ inventory_hostname }}"
    register: is_ip_correct
    ignore_errors: true

  - name: -> Check if the host ip is pinging or not??
    shell: ping -c1 `host {{ inventory_hostname}} | grep "address" |awk '{print $NF}'`
    register: is_ip_reachable
    ignore_errors: True

  - name: -> Failed if host ip is not correctly pinging.
    fail: msg="IP '{{ansible_hostname}}' is not pinging, Please check"
    when: is_ip_reachable|failed
